---
# tasks file for makina-states

# download makina-states
- git: repo="{{makinastates.repo}}"
       dest="{{makinastates.dest}}"
       version="{{makinastates.version}}"

# run setup
- cmd: {{makinastates.path}}/bin/boot-salt.sh -b "{{makinastates.version}}"

# test salt & ansible
- cmd: bin/$item --version
       cwd="{{makinastates.path}}"
  with_items:
    - salt
    - ansible

- include: pillar.yml

