---
## ##
- name: apparmor_ntp_patch
  tags: ms_localsettings_apparmor
  shell: |
         set -e
         test -e /etc/apparmor.d/usr.sbin.ntpd
         if grep -q attach_disconnected /etc/apparmor.d/usr.sbin.ntpd;then
           exit 1
         fi
  register: apparmor_ntp_patch
  ignore_errors: yes
- name: apparmor_ntp_patch-transfer
  tags: ms_localsettings_apparmor
  copy:
    src: "../../../../files/etc/apparmor.d/usr.sbin.ntpd.patch"
    dest: /tmp/apparmor.patch
  when: "apparmor_ntp_patch.rc==0"
- name: apparmor_ntp_patch-apply
  tags: ms_localsettings_apparmor
  shell: |
         set -e
         patch --dry-run -r- -Np2 < /tmp/apparmor.patch
         patch           -r- -Np2 < /tmp/apparmor.patch
  args:
    chdir : /
  when: "apparmor_ntp_patch.rc==0"

## ##
- name: apparmor_ntp_patch2
  tags: ms_localsettings_apparmor
  shell: |
        set -e
        test -e /etc/apparmor.d/usr.sbin.ntpd
        if egrep -q '/\*\*/libopts\*.so\* r,' /etc/apparmor.d/usr.sbin.ntpd;then
          exit 1
        fi
  register: apparmor_ntp_patch2
  ignore_errors: yes
- name: apparmor_ntp_patch-transfer2
  tags: ms_localsettings_apparmor
  copy:
    src: "../../../../files/etc/apparmor.d/usr.sbin.ntpd.perms.patch"
    dest: /tmp/apparmor.patch
  when: "apparmor_ntp_patch2.rc==0"
- name: apparmor_ntp_patch-apply
  tags: ms_localsettings_apparmor
  shell: |
         set -e
         patch --dry-run -r- -Np2 < /tmp/apparmor.patch
         patch           -r- -Np2 < /tmp/apparmor.patch
  args:
    chdir : /
  when: "apparmor_ntp_patch2.rc==0"

